name: Awakening The Architect
favicon: null
layout_spectrum: 0.5908518757205456
typography_spectrum: 0.05581143498420715
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.261644744547084
  lightness: 0.42884722212329507
  saturation: 0.9311145362444222
  rhythmicContrast: 0.9693830329924822
purpose: []
